version: '2.1'
services:
  postgres:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: smartbrew_user
      POSTGRES_PASSWORD: smartbrew
      POSTGRES_DB: smartbrew_database
    ports:
      - '5050:5050'
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql

  server:
    build: .
    ports:
      - 8000:8000
    container_name: server
    restart: always
    depends_on: 
      - postgres
    entrypoint:
    command: sh -c './wait-for db:5432 -- node app.js'
    depends_on:
      - postgres


volumes:
  postgres-data:
