FROM node:16-slim
WORKDIR /usr/src/app
COPY package.json ./
COPY yarn.lock ./
RUN apt-get update
RUN apt-get install -y openssl
RUN yarn --network-timeout 100000
COPY ./ ./
RUN yarn prisma generate
RUN yarn build
ENTRYPOINT ["/bin/sh", "./entrypoint.rpi.sh" ]

