name: Build app

on:
  # listen to manual trigger
  workflow_dispatch:

  # listen to push
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Generate DB schema
        run: yarn prisma generate

      - name: Build app
        run: yarn build
