name: Build and deploy

on:
  # listen to manual trigger
  workflow_dispatch:

  # listen to push
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Generate DB schema
        run: yarn prisma generate

      - name: Build app
        run: yarn build

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  upload-vm:
    needs: [build]
    name: Upload build to Team VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Load build artifacts
        uses: actions/download-artifact@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Add known_hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Rsync to TEAM VM
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -Pav -O --no-perms --delete --exclude="node_modules" --exclude="public" --exclude=".git"
          remote_path: ~/backend/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}

  start-rpi:
    needs: [upload-vm]
    name: Upload to RPI and start docker
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Add known_hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Rsync from TEAM VM to RPI and start docker
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} /bin/bash <<- 'SSH_VM'
            cd ~/
            rsync -Pav -O --no-perms --delete -e "ssh -p 2222" backend/ pi@localhost:/home/pi/backend/
            
            ssh -p 2222 pi@localhost /bin/bash <<- 'SSH_RPI'
              cd /home/pi/backend
              docker-compose -f docker-compose.rpi.yml up --build --detach
          SSH_RPI
          SSH_VM
  
  start-team-vm:
    # TODO remove temporary skip
    if: ${{ false }}
    
    needs: [upload-vm]
    name: Start docker on Team VM
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Add known_hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: SSH to Team VM and start docker
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} /bin/bash <<- 'SSH_VM'
            cd ~/backend
            docker-compose up --build --detach
          SSH_VM

