name: Update Raspberry Pi and run docker

on:
  # listen to manual trigger
  workflow_dispatch:

  # listen to push
  push:
    branches: [main]

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: SSH vm
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }}
      
      - name: List Ub
        run: ls -la
      
      - name: SSH rpi
        run: ssh -p 2222 pi@localhost

      - name: List rpi
        run: ls -la

      - name: Connect SSH and execute script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            ssh -p 2222 pi@localhost
            cd /home/pi/backend
            git pull
            ls -la
            docker-compose build
            docker-compose up --detach
